# Get GINI Index from API

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
# List of Countries most happiest and least happiest countries [kaggle: World Happiest Report]

list_of_names = ['Norway', 'Denmark', 'Iceland', 'Switzerland', 'Finland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'United States', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United Kingdom', 'Chile', 'United Arab Emirates', 'Brazil', 'Czech Republic', 'Argentina', 'Mexico', 'Singapore', 'Malta', 'Uruguay', 'Guatemala', 'Panama', 'France', 'Thailand', 'Spain', 'Qatar', 'Colombia', 'Saudi Arabia', 'Trinidad and Tobago', 'Kuwait', 'Slovakia', 'Bahrain', 'Malaysia', 'Nicaragua', 'Ecuador', 'El Salvador', 'Poland', 'Uzbekistan', 'Italy', 'Russia', 'Belize', 'Japan', 'Lithuania', 'Algeria', 'Latvia', 'Moldova', 'Romania', 'Bolivia', 'Turkmenistan', 'Kazakhstan', 'Slovenia', 'Peru', 'Mauritius', 'Cyprus', 'Estonia', 'Belarus', 'Libya', 'Turkey', 'Paraguay', 'Philippines', 'Serbia', 'Jordan', 'Hungary', 'Jamaica', 'Croatia', 'Kosovo', 'China', 'Pakistan', 'Indonesia', 'Venezuela', 'Montenegro', 'Morocco', 'Azerbaijan', 'Dominican Republic', 'Greece', 'Lebanon', 'Portugal', 'Bosnia and Herzegovina', 'Honduras', 'Macedonia', 'Somalia', 'Vietnam', 'Nigeria', 'Tajikistan', 'Bhutan', 'Kyrgyzstan', 'Nepal', 'Mongolia', 'South Africa', 'Tunisia', 'Egypt', 'Bulgaria', 'Sierra Leone', 'Cameroon', 'Iran', 'Albania', 'Bangladesh', 'Namibia', 'Kenya', 'Mozambique', 'Myanmar', 'Senegal', 'Zambia', 'Iraq', 'Gabon', 'Ethiopia', 'Sri Lanka', 'Armenia', 'India', 'Mauritania', 'Mali', 'Ivory Coast', 'Cambodia', 'Sudan', 'Ghana', 'Ukraine', 'Uganda', 'Burkina Faso', 'Niger', 'Malawi', 'Chad', 'Zimbabwe', 'Lesotho', 'Angola', 'Afghanistan', 'Botswana', 'Benin', 'Madagascar', 'Haiti', 'Yemen', 'South Sudan', 'Liberia', 'Guinea', 'Togo', 'Rwanda', 'Syria', 'Tanzania', 'Burundi', 'Central African Republic']

fields = "?fields=alpha3Code;name"
url = "https://restcountries.eu/rest/v2/name/"



contents = [requests.get(url + list_of_names[x] + fields).json() for x in range(len(list_of_names))]

print(contents)

[[{'name': 'Norway', 'alpha3Code': 'NOR'}], [{'name': 'Denmark', 'alpha3Code': 'DNK'}], [{'name': 'Iceland', 'alpha3Code': 'ISL'}], [{'name': 'Switzerland', 'alpha3Code': 'CHE'}], [{'name': 'Finland', 'alpha3Code': 'FIN'}], [{'name': 'Netherlands', 'alpha3Code': 'NLD'}], [{'name': 'Canada', 'alpha3Code': 'CAN'}], [{'name': 'New Zealand', 'alpha3Code': 'NZL'}], [{'name': 'Sweden', 'alpha3Code': 'SWE'}], [{'name': 'Australia', 'alpha3Code': 'AUS'}], [{'name': 'Israel', 'alpha3Code': 'ISR'}], [{'name': 'Costa Rica', 'alpha3Code': 'CRI'}], [{'name': 'Austria', 'alpha3Code': 'AUT'}], [{'name': 'United States Minor Outlying Islands', 'alpha3Code': 'UMI'}, {'name': 'United States of America', 'alpha3Code': 'USA'}], [{'name': 'Ireland', 'alpha3Code': 'IRL'}, {'name': 'United Kingdom of Great Britain and Northern Ireland', 'alpha3Code': 'GBR'}], [{'name': 'Germany', 'alpha3Code': 'DEU'}], [{'name': 'Belgium', 'alpha3Code': 'BEL'}], [{'name': 'Luxembourg', 'alpha3Code': 'LUX'}], [{'name': 'United Kingdom of Great Britain and Northern Ireland', 'alpha3Code': 'GBR'}], [{'name': 'Chile', 'alpha3Code': 'CHL'}], [{'name': 'United Arab Emirates', 'alpha3Code': 'ARE'}], [{'name': 'Brazil', 'alpha3Code': 'BRA'}], [{'name': 'Czech Republic', 'alpha3Code': 'CZE'}], [{'name': 'Argentina', 'alpha3Code': 'ARG'}], [{'name': 'Mexico', 'alpha3Code': 'MEX'}], [{'name': 'Singapore', 'alpha3Code': 'SGP'}], [{'name': 'Malta', 'alpha3Code': 'MLT'}], [{'name': 'Uruguay', 'alpha3Code': 'URY'}], [{'name': 'Guatemala', 'alpha3Code': 'GTM'}], [{'name': 'Panama', 'alpha3Code': 'PAN'}], [{'name': 'France', 'alpha3Code': 'FRA'}], [{'name': 'Thailand', 'alpha3Code': 'THA'}], [{'name': 'Spain', 'alpha3Code': 'ESP'}], [{'name': 'Qatar', 'alpha3Code': 'QAT'}], [{'name': 'Colombia', 'alpha3Code': 'COL'}], [{'name': 'Saudi Arabia', 'alpha3Code': 'SAU'}], [{'name': 'Trinidad and Tobago', 'alpha3Code': 'TTO'}], [{'name': 'Kuwait', 'alpha3Code': 'KWT'}], [{'name': 'Slovakia', 'alpha3Code': 'SVK'}], [{'name': 'Bahrain', 'alpha3Code': 'BHR'}], [{'name': 'Malaysia', 'alpha3Code': 'MYS'}], [{'name': 'Nicaragua', 'alpha3Code': 'NIC'}], [{'name': 'Ecuador', 'alpha3Code': 'ECU'}], [{'name': 'El Salvador', 'alpha3Code': 'SLV'}], [{'name': 'Poland', 'alpha3Code': 'POL'}], [{'name': 'Uzbekistan', 'alpha3Code': 'UZB'}], [{'name': 'Italy', 'alpha3Code': 'ITA'}], [{'name': 'Russian Federation', 'alpha3Code': 'RUS'}], [{'name': 'Belize', 'alpha3Code': 'BLZ'}], [{'name': 'Japan', 'alpha3Code': 'JPN'}], [{'name': 'Lithuania', 'alpha3Code': 'LTU'}], [{'name': 'Algeria', 'alpha3Code': 'DZA'}], [{'name': 'Latvia', 'alpha3Code': 'LVA'}], [{'name': 'Moldova (Republic of)', 'alpha3Code': 'MDA'}], [{'name': 'Romania', 'alpha3Code': 'ROU'}], [{'name': 'Bolivia (Plurinational State of)', 'alpha3Code': 'BOL'}], [{'name': 'Turkmenistan', 'alpha3Code': 'TKM'}], [{'name': 'Kazakhstan', 'alpha3Code': 'KAZ'}], [{'name': 'Slovenia', 'alpha3Code': 'SVN'}], [{'name': 'Peru', 'alpha3Code': 'PER'}], [{'name': 'Mauritius', 'alpha3Code': 'MUS'}], [{'name': 'Cyprus', 'alpha3Code': 'CYP'}], [{'name': 'Estonia', 'alpha3Code': 'EST'}], [{'name': 'Belarus', 'alpha3Code': 'BLR'}], [{'name': 'Libya', 'alpha3Code': 'LBY'}], [{'name': 'Turkey', 'alpha3Code': 'TUR'}], [{'name': 'Paraguay', 'alpha3Code': 'PRY'}], [{'name': 'Philippines', 'alpha3Code': 'PHL'}], [{'name': 'Serbia', 'alpha3Code': 'SRB'}], [{'name': 'Jordan', 'alpha3Code': 'JOR'}], [{'name': 'Hungary', 'alpha3Code': 'HUN'}], [{'name': 'Jamaica', 'alpha3Code': 'JAM'}], [{'name': 'Croatia', 'alpha3Code': 'HRV'}], [{'name': 'Republic of Kosovo', 'alpha3Code': 'KOS'}], [{'name': 'China', 'alpha3Code': 'CHN'}, {'name': 'Macao', 'alpha3Code': 'MAC'}, {'name': 'Taiwan', 'alpha3Code': 'TWN'}], [{'name': 'Pakistan', 'alpha3Code': 'PAK'}], [{'name': 'Indonesia', 'alpha3Code': 'IDN'}], [{'name': 'Venezuela (Bolivarian Republic of)', 'alpha3Code': 'VEN'}], [{'name': 'Montenegro', 'alpha3Code': 'MNE'}], [{'name': 'Morocco', 'alpha3Code': 'MAR'}], [{'name': 'Azerbaijan', 'alpha3Code': 'AZE'}], [{'name': 'Dominican Republic', 'alpha3Code': 'DOM'}], [{'name': 'Greece', 'alpha3Code': 'GRC'}], [{'name': 'Lebanon', 'alpha3Code': 'LBN'}], [{'name': 'Portugal', 'alpha3Code': 'PRT'}], [{'name': 'Bosnia and Herzegovina', 'alpha3Code': 'BIH'}], [{'name': 'Honduras', 'alpha3Code': 'HND'}], [{'name': 'Macedonia (the former Yugoslav Republic of)', 'alpha3Code': 'MKD'}], [{'name': 'Somalia', 'alpha3Code': 'SOM'}], [{'name': 'Viet Nam', 'alpha3Code': 'VNM'}], [{'name': 'Nigeria', 'alpha3Code': 'NGA'}], [{'name': 'Tajikistan', 'alpha3Code': 'TJK'}], [{'name': 'Bhutan', 'alpha3Code': 'BTN'}], [{'name': 'Kyrgyzstan', 'alpha3Code': 'KGZ'}], [{'name': 'Nepal', 'alpha3Code': 'NPL'}], [{'name': 'Mongolia', 'alpha3Code': 'MNG'}], [{'name': 'South Africa', 'alpha3Code': 'ZAF'}], [{'name': 'Tunisia', 'alpha3Code': 'TUN'}], [{'name': 'Egypt', 'alpha3Code': 'EGY'}], [{'name': 'Bulgaria', 'alpha3Code': 'BGR'}], [{'name': 'Sierra Leone', 'alpha3Code': 'SLE'}], [{'name': 'Cameroon', 'alpha3Code': 'CMR'}], [{'name': 'Iran (Islamic Republic of)', 'alpha3Code': 'IRN'}, {'name': 'Cook Islands', 'alpha3Code': 'COK'}], [{'name': 'Albania', 'alpha3Code': 'ALB'}], [{'name': 'Bangladesh', 'alpha3Code': 'BGD'}], [{'name': 'Namibia', 'alpha3Code': 'NAM'}], [{'name': 'Kenya', 'alpha3Code': 'KEN'}], [{'name': 'Mozambique', 'alpha3Code': 'MOZ'}], [{'name': 'Myanmar', 'alpha3Code': 'MMR'}], [{'name': 'Senegal', 'alpha3Code': 'SEN'}], [{'name': 'Zambia', 'alpha3Code': 'ZMB'}], [{'name': 'Iraq', 'alpha3Code': 'IRQ'}], [{'name': 'Gabon', 'alpha3Code': 'GAB'}], [{'name': 'Ethiopia', 'alpha3Code': 'ETH'}], [{'name': 'Sri Lanka', 'alpha3Code': 'LKA'}], [{'name': 'Armenia', 'alpha3Code': 'ARM'}], [{'name': 'British Indian Ocean Territory', 'alpha3Code': 'IOT'}, {'name': 'India', 'alpha3Code': 'IND'}], [{'name': 'Mauritania', 'alpha3Code': 'MRT'}], [{'name': 'Mali', 'alpha3Code': 'MLI'}, {'name': 'Somalia', 'alpha3Code': 'SOM'}], [{'name': "CÃ´te d'Ivoire", 'alpha3Code': 'CIV'}], [{'name': 'Cambodia', 'alpha3Code': 'KHM'}], [{'name': 'South Sudan', 'alpha3Code': 'SSD'}, {'name': 'Sudan', 'alpha3Code': 'SDN'}], [{'name': 'Ghana', 'alpha3Code': 'GHA'}], [{'name': 'Ukraine', 'alpha3Code': 'UKR'}], [{'name': 'Uganda', 'alpha3Code': 'UGA'}], [{'name': 'Burkina Faso', 'alpha3Code': 'BFA'}], [{'name': 'Niger', 'alpha3Code': 'NER'}, {'name': 'Nigeria', 'alpha3Code': 'NGA'}], [{'name': 'Malawi', 'alpha3Code': 'MWI'}], [{'name': 'Chad', 'alpha3Code': 'TCD'}], [{'name': 'Zimbabwe', 'alpha3Code': 'ZWE'}], [{'name': 'Lesotho', 'alpha3Code': 'LSO'}], [{'name': 'Angola', 'alpha3Code': 'AGO'}], [{'name': 'Afghanistan', 'alpha3Code': 'AFG'}], [{'name': 'Botswana', 'alpha3Code': 'BWA'}], [{'name': 'Benin', 'alpha3Code': 'BEN'}], [{'name': 'Madagascar', 'alpha3Code': 'MDG'}], [{'name': 'Haiti', 'alpha3Code': 'HTI'}], [{'name': 'Yemen', 'alpha3Code': 'YEM'}], [{'name': 'South Sudan', 'alpha3Code': 'SSD'}], [{'name': 'Liberia', 'alpha3Code': 'LBR'}], [{'name': 'Equatorial Guinea', 'alpha3Code': 'GNQ'}, {'name': 'Guinea', 'alpha3Code': 'GIN'}, {'name': 'Guinea-Bissau', 'alpha3Code': 'GNB'}, {'name': 'Papua New Guinea', 'alpha3Code': 'PNG'}], [{'name': 'Togo', 'alpha3Code': 'TGO'}], [{'name': 'Rwanda', 'alpha3Code': 'RWA'}], [{'name': 'Syrian Arab Republic', 'alpha3Code': 'SYR'}], [{'name': 'Tanzania, United Republic of', 'alpha3Code': 'TZA'}], [{'name': 'Burundi', 'alpha3Code': 'BDI'}], [{'name': 'Central African Republic', 'alpha3Code': 'CAF'}]]

In [3]:
d_contents = pd.DataFrame(contents)
d_contents[30:120]

#[ d_contents[i]  for i in range(len(d_contents))if d_contents[i]=="status"]

,0,1,2,3
30,"{'name': 'France', 'alpha3Code': 'FRA'}",None,None,None
31,"{'name': 'Thailand', 'alpha3Code': 'THA'}",None,None,None
32,"{'name': 'Spain', 'alpha3Code': 'ESP'}",None,None,None
33,"{'name': 'Qatar', 'alpha3Code': 'QAT'}",None,None,None
34,"{'name': 'Colombia', 'alpha3Code': 'COL'}",None,None,None
35,"{'name': 'Saudi Arabia', 'alpha3Code': 'SAU'}",None,None,None
36,"{'name': 'Trinidad and Tobago', 'alpha3Code': ...",None,None,None
37,"{'name': 'Kuwait', 'alpha3Code': 'KWT'}",None,None,None
38,"{'name': 'Slovakia', 'alpha3Code': 'SVK'}",None,None,None
39,"{'name': 'Bahrain', 'alpha3Code': 'BHR'}",None,None,None
40,"{'name': 'Malaysia', 'alpha3Code': 'MYS'}",None,None,None
41,"{'name': 'Nicaragua', 'alpha3Code': 'NIC'}",None,None,None
42,"{'name': 'Ecuador', 'alpha3Code': 'ECU'}",None,None,None
43,"{'name': 'El Salvador', 'alpha3Code': 'SLV'}",None,None,None
44,"{'name': 'Poland', 'alpha3Code': 'POL'}",None,None,None
45,"{'name': 'Uzbekistan', 'alpha3Code': 'UZB'}",None,None,None
46,"{'name': 'Italy', 'alpha3Code': 'ITA'}",None,None,None
47,"{'name': 'Russian Federation', 'alpha3Code': '...",None,None,None
48,"{'name': 'Belize', 'alpha3Code': 'BLZ'}",None,None,None
49,"{'name': 'Japan', 'alpha3Code': 'JPN'}",None,None,None
50,"{'name': 'Lithuania', 'alpha3Code': 'LTU'}",None,None,None
51,"{'name': 'Algeria', 'alpha3Code': 'DZA'}",None,None,None
52,"{'name': 'Latvia', 'alpha3Code': 'LVA'}",None,None,None
53,"{'name': 'Moldova (Republic of)', 'alpha3Code'...",None,None,None
54,"{'name': 'Romania', 'alpha3Code': 'ROU'}",None,None,None
55,"{'name': 'Bolivia (Plurinational State of)', '...",None,None,None
56,"{'name': 'Turkmenistan', 'alpha3Code': 'TKM'}",None,None,None
57,"{'name': 'Kazakhstan', 'alpha3Code': 'KAZ'}",None,None,None
58,"{'name': 'Slovenia', 'alpha3Code': 'SVN'}",None,None,None
59,"{'name': 'Peru', 'alpha3Code': 'PER'}",None,None,None
...,...,...,...,...
90,"{'name': 'Nigeria', 'alpha3Code': 'NGA'}",None,None,None
91,"{'name': 'Tajikistan', 'alpha3Code': 'TJK'}",None,None,None
92,"{'name': 'Bhutan', 'alpha3Code': 'BTN'}",None,None,None
93,"{'name': 'Kyrgyzstan', 'alpha3Code': 'KGZ'}",None,None,None
94,"{'name': 'Nepal', 'alpha3Code': 'NPL'}",None,None,None
95,"{'name': 'Mongolia', 'alpha3Code': 'MNG'}",None,None,None
96,"{'name': 'South Africa', 'alpha3Code': 'ZAF'}",None,None,None
97,"{'name': 'Tunisia', 'alpha3Code': 'TUN'}",None,None,None
98,"{'name': 'Egypt', 'alpha3Code': 'EGY'}",None,None,None
99,"{'name': 'Bulgaria', 'alpha3Code': 'BGR'}",None,None,None
100,"{'name': 'Sierra Leone', 'alpha3Code': 'SLE'}",None,None,None
101,"{'name': 'Cameroon', 'alpha3Code': 'CMR'}",None,None,None
102,"{'name': 'Iran (Islamic Republic of)', 'alpha3...","{'name': 'Cook Islands', 'alpha3Code': 'COK'}",None,None
103,"{'name': 'Albania', 'alpha3Code': 'ALB'}",None,None,None
104,"{'name': 'Bangladesh', 'alpha3Code': 'BGD'}",None,None,None
105,"{'name': 'Namibia', 'alpha3Code': 'NAM'}",None,None,None
106,"{'name': 'Kenya', 'alpha3Code': 'KEN'}",None,None,None
107,"{'name': 'Mozambique', 'alpha3Code': 'MOZ'}",None,None,None
108,"{'name': 'Myanmar', 'alpha3Code': 'MMR'}",None,None,None
109,"{'name': 'Senegal', 'alpha3Code': 'SEN'}",None,None,None
110,"{'name': 'Zambia', 'alpha3Code': 'ZMB'}",None,None,None
111,"{'name': 'Iraq', 'alpha3Code': 'IRQ'}",None,None,None
112,"{'name': 'Gabon', 'alpha3Code': 'GAB'}",None,None,None
113,"{'name': 'Ethiopia', 'alpha3Code': 'ETH'}",None,None,None
114,"{'name': 'Sri Lanka', 'alpha3Code': 'LKA'}",None,None,None
115,"{'name': 'Armenia', 'alpha3Code': 'ARM'}",None,None,None
116,"{'name': 'British Indian Ocean Territory', 'al...","{'name': 'India', 'alpha3Code': 'IND'}",None,None
117,"{'name': 'Mauritania', 'alpha3Code': 'MRT'}",None,None,None
118,"{'name': 'Mali', 'alpha3Code': 'MLI'}","{'name': 'Somalia', 'alpha3Code': 'SOM'}",None,None
119,"{'name': 'CÃ´te d'Ivoire', 'alpha3Code': 'CIV'}",None,None,None

In [4]:
# Extend Country name with Code (alpha3Code) [Source: API]

country_code =[d_contents[0][i] for i in range(len(d_contents))]
ds = pd.DataFrame.from_dict([country_code[i] for i in range(len(d_contents))])
ds

    alpha3Code                                               name
0          NOR                                             Norway
1          DNK                                            Denmark
2          ISL                                            Iceland
3          CHE                                        Switzerland
4          FIN                                            Finland
5          NLD                                        Netherlands
6          CAN                                             Canada
7          NZL                                        New Zealand
8          SWE                                             Sweden
9          AUS                                          Australia
10         ISR                                             Israel
11         CRI                                         Costa Rica
12         AUT                                            Austria
13         UMI               United States Minor Outlying Islands
14         IRL                                            Ireland
15         DEU                                            Germany
16         BEL                                            Belgium
17         LUX                                         Luxembourg
18         GBR  United Kingdom of Great Britain and Northern I...
19         CHL                                              Chile
20         ARE                               United Arab Emirates
21         BRA                                             Brazil
22         CZE                                     Czech Republic
23         ARG                                          Argentina
24         MEX                                             Mexico
25         SGP                                          Singapore
26         MLT                                              Malta
27         URY                                            Uruguay
28         GTM                                          Guatemala
29         PAN                                             Panama
..         ...                                                ...
117        MRT                                         Mauritania
118        MLI                                               Mali
119        CIV                                      CÃ´te d'Ivoire
120        KHM                                           Cambodia
121        SSD                                        South Sudan
122        GHA                                              Ghana
123        UKR                                            Ukraine
124        UGA                                             Uganda
125        BFA                                       Burkina Faso
126        NER                                              Niger
127        MWI                                             Malawi
128        TCD                                               Chad
129        ZWE                                           Zimbabwe
130        LSO                                            Lesotho
131        AGO                                             Angola
132        AFG                                        Afghanistan
133        BWA                                           Botswana
134        BEN                                              Benin
135        MDG                                         Madagascar
136        HTI                                              Haiti
137        YEM                                              Yemen
138        SSD                                        South Sudan
139        LBR                                            Liberia
140        GNQ                                  Equatorial Guinea
141        TGO                                               Togo
142        RWA                                             Rwanda
143        SYR                               Syrian Arab Republic
144        TZA                       Tanzania, United Republic of
145        BDI                                            Burundi
146        CAF                           Central African Republic

[147 rows x 2 columns]

In [5]:
# Merge Data of API (Gini-Index) with Country Name (WH-Report)

codes = list(ds["alpha3Code"])
codes

fields2 = "?fields=gini;name"
url2 = "https://restcountries.eu/rest/v2/alpha/"

ginis = [requests.get(url2 + codes[x] + fields2).content for x in range(len(codes))]

print(ginis)

[b'{"name":"Norway","gini":25.8}', b'{"name":"Denmark","gini":24.0}', b'{"name":"Iceland"}', b'{"name":"Switzerland","gini":33.7}', b'{"name":"Finland","gini":26.9}', b'{"name":"Netherlands","gini":30.9}', b'{"name":"Canada","gini":32.6}', b'{"name":"New Zealand","gini":36.2}', b'{"name":"Sweden","gini":25.0}', b'{"name":"Australia","gini":30.5}', b'{"name":"Israel","gini":39.2}', b'{"name":"Costa Rica","gini":50.7}', b'{"name":"Austria","gini":26.0}', b'{"name":"United States Minor Outlying Islands"}', b'{"name":"Ireland","gini":34.3}', b'{"name":"Germany","gini":28.3}', b'{"name":"Belgium","gini":33.0}', b'{"name":"Luxembourg","gini":30.8}', b'{"name":"United Kingdom of Great Britain and Northern Ireland","gini":34.0}', b'{"name":"Chile","gini":52.1}', b'{"name":"United Arab Emirates"}', b'{"name":"Brazil","gini":54.7}', b'{"name":"Czech Republic","gini":26.0}', b'{"name":"Argentina","gini":44.5}', b'{"name":"Mexico","gini":47.0}', b'{"name":"Singapore","gini":48.1}', b'{"name":"Malta"}', b'{"name":"Uruguay","gini":39.7}', b'{"name":"Guatemala","gini":55.9}', b'{"name":"Panama","gini":51.9}', b'{"name":"France","gini":32.7}', b'{"name":"Thailand","gini":40.0}', b'{"name":"Spain","gini":34.7}', b'{"name":"Qatar","gini":41.1}', b'{"name":"Colombia","gini":55.9}', b'{"name":"Saudi Arabia"}', b'{"name":"Trinidad and Tobago","gini":40.3}', b'{"name":"Kuwait"}', b'{"name":"Slovakia","gini":26.0}', b'{"name":"Bahrain"}', b'{"name":"Malaysia","gini":46.2}', b'{"name":"Nicaragua","gini":40.5}', b'{"name":"Ecuador","gini":49.3}', b'{"name":"El Salvador","gini":48.3}', b'{"name":"Poland","gini":34.1}', b'{"name":"Uzbekistan","gini":36.7}', b'{"name":"Italy","gini":36.0}', b'{"name":"Russian Federation","gini":40.1}', b'{"name":"Belize","gini":53.1}', b'{"name":"Japan","gini":38.1}', b'{"name":"Lithuania","gini":37.6}', b'{"name":"Algeria","gini":35.3}', b'{"name":"Latvia","gini":36.6}', b'{"name":"Moldova (Republic of)","gini":33.0}', b'{"name":"Romania","gini":30.0}', b'{"name":"Bolivia (Plurinational State of)","gini":56.3}', b'{"name":"Turkmenistan","gini":40.8}', b'{"name":"Kazakhstan","gini":29.0}', b'{"name":"Slovenia","gini":31.2}', b'{"name":"Peru","gini":48.1}', b'{"name":"Mauritius"}', b'{"name":"Cyprus"}', b'{"name":"Estonia","gini":36.0}', b'{"name":"Belarus","gini":26.5}', b'{"name":"Libya"}', b'{"name":"Turkey","gini":39.0}', b'{"name":"Paraguay","gini":52.4}', b'{"name":"Philippines","gini":43.0}', b'{"name":"Serbia","gini":27.8}', b'{"name":"Jordan","gini":35.4}', b'{"name":"Hungary","gini":31.2}', b'{"name":"Jamaica","gini":45.5}', b'{"name":"Croatia","gini":33.7}', b'{"name":"Republic of Kosovo"}', b'{"name":"China","gini":47.0}', b'{"name":"Pakistan","gini":30.0}', b'{"name":"Indonesia","gini":34.0}', b'{"name":"Venezuela (Bolivarian Republic of)","gini":44.8}', b'{"name":"Montenegro","gini":30.0}', b'{"name":"Morocco","gini":40.9}', b'{"name":"Azerbaijan","gini":33.7}', b'{"name":"Dominican Republic","gini":47.2}', b'{"name":"Greece","gini":34.3}', b'{"name":"Lebanon"}', b'{"name":"Portugal","gini":38.5}', b'{"name":"Bosnia and Herzegovina","gini":36.2}', b'{"name":"Honduras","gini":57.0}', b'{"name":"Macedonia (the former Yugoslav Republic of)","gini":43.2}', b'{"name":"Somalia"}', b'{"name":"Viet Nam","gini":35.6}', b'{"name":"Nigeria","gini":48.8}', b'{"name":"Tajikistan","gini":30.8}', b'{"name":"Bhutan","gini":38.1}', b'{"name":"Kyrgyzstan","gini":36.2}', b'{"name":"Nepal","gini":32.8}', b'{"name":"Mongolia","gini":36.5}', b'{"name":"South Africa","gini":63.1}', b'{"name":"Tunisia","gini":41.4}', b'{"name":"Egypt","gini":30.8}', b'{"name":"Bulgaria","gini":28.2}', b'{"name":"Sierra Leone","gini":42.5}', b'{"name":"Cameroon","gini":38.9}', b'{"name":"Iran (Islamic Republic of)","gini":38.3}', b'{"name":"Albania","gini":34.5}', b'{"name":"Bangladesh","gini":32.1}', b'{"name":"Namibia","gini":63.9}', b'{"name":"Kenya","gini":47.7}', b'{"name":"Mozambique","gini":45.7}', b'{"name":"Myanmar"}', b'{"name":"Senegal","gini":39.2}', b'{"name":"Zambia","gini":54.6}', b'{"name":"Iraq","gini":30.9}', b'{"name":"Gabon","gini":41.5}', b'{"name":"Ethiopia","gini":29.8}', b'{"name":"Sri Lanka","gini":40.3}', b'{"name":"Armenia","gini":30.9}', b'{"name":"British Indian Ocean Territory"}', b'{"name":"Mauritania","gini":40.5}', b'{"name":"Mali","gini":33.0}', b'{"name":"C\xc3\xb4te d\'Ivoire","gini":41.5}', b'{"name":"Cambodia","gini":37.9}', b'{"name":"South Sudan","gini":45.5}', b'{"name":"Ghana","gini":42.8}', b'{"name":"Ukraine","gini":26.4}', b'{"name":"Uganda","gini":44.3}', b'{"name":"Burkina Faso","gini":39.8}', b'{"name":"Niger","gini":34.6}', b'{"name":"Malawi","gini":39.0}', b'{"name":"Chad","gini":39.8}', b'{"name":"Zimbabwe"}', b'{"name":"Lesotho","gini":52.5}', b'{"name":"Angola","gini":58.6}', b'{"name":"Afghanistan","gini":27.8}', b'{"name":"Botswana","gini":61.0}', b'{"name":"Benin","gini":38.6}', b'{"name":"Madagascar","gini":44.1}', b'{"name":"Haiti","gini":59.2}', b'{"name":"Yemen","gini":37.7}', b'{"name":"South Sudan","gini":45.5}', b'{"name":"Liberia","gini":38.2}', b'{"name":"Equatorial Guinea"}', b'{"name":"Togo","gini":34.4}', b'{"name":"Rwanda","gini":50.8}', b'{"name":"Syrian Arab Republic","gini":35.8}', b'{"name":"Tanzania, United Republic of","gini":37.6}', b'{"name":"Burundi","gini":33.3}', b'{"name":"Central African Republic","gini":56.3}']

In [6]:
# Transformation

new =[ginis[i] for i in range(len(d_contents))]
new[0]
new1 = [str(new[i]).replace("b'","").replace("'", "") for i in range(len(new))]
print(new1)
new1[0]

import ast

dict_gini = [ast.literal_eval(new1[i]) for i in range(len(new1))]

['{"name":"Norway","gini":25.8}', '{"name":"Denmark","gini":24.0}', '{"name":"Iceland"}', '{"name":"Switzerland","gini":33.7}', '{"name":"Finland","gini":26.9}', '{"name":"Netherlands","gini":30.9}', '{"name":"Canada","gini":32.6}', '{"name":"New Zealand","gini":36.2}', '{"name":"Sweden","gini":25.0}', '{"name":"Australia","gini":30.5}', '{"name":"Israel","gini":39.2}', '{"name":"Costa Rica","gini":50.7}', '{"name":"Austria","gini":26.0}', '{"name":"United States Minor Outlying Islands"}', '{"name":"Ireland","gini":34.3}', '{"name":"Germany","gini":28.3}', '{"name":"Belgium","gini":33.0}', '{"name":"Luxembourg","gini":30.8}', '{"name":"United Kingdom of Great Britain and Northern Ireland","gini":34.0}', '{"name":"Chile","gini":52.1}', '{"name":"United Arab Emirates"}', '{"name":"Brazil","gini":54.7}', '{"name":"Czech Republic","gini":26.0}', '{"name":"Argentina","gini":44.5}', '{"name":"Mexico","gini":47.0}', '{"name":"Singapore","gini":48.1}', '{"name":"Malta"}', '{"name":"Uruguay","gini":39.7}', '{"name":"Guatemala","gini":55.9}', '{"name":"Panama","gini":51.9}', '{"name":"France","gini":32.7}', '{"name":"Thailand","gini":40.0}', '{"name":"Spain","gini":34.7}', '{"name":"Qatar","gini":41.1}', '{"name":"Colombia","gini":55.9}', '{"name":"Saudi Arabia"}', '{"name":"Trinidad and Tobago","gini":40.3}', '{"name":"Kuwait"}', '{"name":"Slovakia","gini":26.0}', '{"name":"Bahrain"}', '{"name":"Malaysia","gini":46.2}', '{"name":"Nicaragua","gini":40.5}', '{"name":"Ecuador","gini":49.3}', '{"name":"El Salvador","gini":48.3}', '{"name":"Poland","gini":34.1}', '{"name":"Uzbekistan","gini":36.7}', '{"name":"Italy","gini":36.0}', '{"name":"Russian Federation","gini":40.1}', '{"name":"Belize","gini":53.1}', '{"name":"Japan","gini":38.1}', '{"name":"Lithuania","gini":37.6}', '{"name":"Algeria","gini":35.3}', '{"name":"Latvia","gini":36.6}', '{"name":"Moldova (Republic of)","gini":33.0}', '{"name":"Romania","gini":30.0}', '{"name":"Bolivia (Plurinational State of)","gini":56.3}', '{"name":"Turkmenistan","gini":40.8}', '{"name":"Kazakhstan","gini":29.0}', '{"name":"Slovenia","gini":31.2}', '{"name":"Peru","gini":48.1}', '{"name":"Mauritius"}', '{"name":"Cyprus"}', '{"name":"Estonia","gini":36.0}', '{"name":"Belarus","gini":26.5}', '{"name":"Libya"}', '{"name":"Turkey","gini":39.0}', '{"name":"Paraguay","gini":52.4}', '{"name":"Philippines","gini":43.0}', '{"name":"Serbia","gini":27.8}', '{"name":"Jordan","gini":35.4}', '{"name":"Hungary","gini":31.2}', '{"name":"Jamaica","gini":45.5}', '{"name":"Croatia","gini":33.7}', '{"name":"Republic of Kosovo"}', '{"name":"China","gini":47.0}', '{"name":"Pakistan","gini":30.0}', '{"name":"Indonesia","gini":34.0}', '{"name":"Venezuela (Bolivarian Republic of)","gini":44.8}', '{"name":"Montenegro","gini":30.0}', '{"name":"Morocco","gini":40.9}', '{"name":"Azerbaijan","gini":33.7}', '{"name":"Dominican Republic","gini":47.2}', '{"name":"Greece","gini":34.3}', '{"name":"Lebanon"}', '{"name":"Portugal","gini":38.5}', '{"name":"Bosnia and Herzegovina","gini":36.2}', '{"name":"Honduras","gini":57.0}', '{"name":"Macedonia (the former Yugoslav Republic of)","gini":43.2}', '{"name":"Somalia"}', '{"name":"Viet Nam","gini":35.6}', '{"name":"Nigeria","gini":48.8}', '{"name":"Tajikistan","gini":30.8}', '{"name":"Bhutan","gini":38.1}', '{"name":"Kyrgyzstan","gini":36.2}', '{"name":"Nepal","gini":32.8}', '{"name":"Mongolia","gini":36.5}', '{"name":"South Africa","gini":63.1}', '{"name":"Tunisia","gini":41.4}', '{"name":"Egypt","gini":30.8}', '{"name":"Bulgaria","gini":28.2}', '{"name":"Sierra Leone","gini":42.5}', '{"name":"Cameroon","gini":38.9}', '{"name":"Iran (Islamic Republic of)","gini":38.3}', '{"name":"Albania","gini":34.5}', '{"name":"Bangladesh","gini":32.1}', '{"name":"Namibia","gini":63.9}', '{"name":"Kenya","gini":47.7}', '{"name":"Mozambique","gini":45.7}', '{"name":"Myanmar"}', '{"name":"Senegal","gini":39.2}', '{"name":"Zambia","gini":54.6}', '{"name":"Iraq","gini":30.9}', '{"name":"Gabon","gini":41.5}', '{"name":"Ethiopia","gini":29.8}', '{"name":"Sri Lanka","gini":40.3}', '{"name":"Armenia","gini":30.9}', '{"name":"British Indian Ocean Territory"}', '{"name":"Mauritania","gini":40.5}', '{"name":"Mali","gini":33.0}', '{"name":"C\\xc3\\xb4te d\\Ivoire","gini":41.5}', '{"name":"Cambodia","gini":37.9}', '{"name":"South Sudan","gini":45.5}', '{"name":"Ghana","gini":42.8}', '{"name":"Ukraine","gini":26.4}', '{"name":"Uganda","gini":44.3}', '{"name":"Burkina Faso","gini":39.8}', '{"name":"Niger","gini":34.6}', '{"name":"Malawi","gini":39.0}', '{"name":"Chad","gini":39.8}', '{"name":"Zimbabwe"}', '{"name":"Lesotho","gini":52.5}', '{"name":"Angola","gini":58.6}', '{"name":"Afghanistan","gini":27.8}', '{"name":"Botswana","gini":61.0}', '{"name":"Benin","gini":38.6}', '{"name":"Madagascar","gini":44.1}', '{"name":"Haiti","gini":59.2}', '{"name":"Yemen","gini":37.7}', '{"name":"South Sudan","gini":45.5}', '{"name":"Liberia","gini":38.2}', '{"name":"Equatorial Guinea"}', '{"name":"Togo","gini":34.4}', '{"name":"Rwanda","gini":50.8}', '{"name":"Syrian Arab Republic","gini":35.8}', '{"name":"Tanzania, United Republic of","gini":37.6}', '{"name":"Burundi","gini":33.3}', '{"name":"Central African Republic","gini":56.3}']

In [7]:
# Connect Gini-Index with Country Name

ds_gini = pd.DataFrame.from_dict([dict_gini[i] for i in range(len(new1))])
ds_gini

     gini                                               name
0    25.8                                             Norway
1    24.0                                            Denmark
2     NaN                                            Iceland
3    33.7                                        Switzerland
4    26.9                                            Finland
5    30.9                                        Netherlands
6    32.6                                             Canada
7    36.2                                        New Zealand
8    25.0                                             Sweden
9    30.5                                          Australia
10   39.2                                             Israel
11   50.7                                         Costa Rica
12   26.0                                            Austria
13    NaN               United States Minor Outlying Islands
14   34.3                                            Ireland
15   28.3                                            Germany
16   33.0                                            Belgium
17   30.8                                         Luxembourg
18   34.0  United Kingdom of Great Britain and Northern I...
19   52.1                                              Chile
20    NaN                               United Arab Emirates
21   54.7                                             Brazil
22   26.0                                     Czech Republic
23   44.5                                          Argentina
24   47.0                                             Mexico
25   48.1                                          Singapore
26    NaN                                              Malta
27   39.7                                            Uruguay
28   55.9                                          Guatemala
29   51.9                                             Panama
..    ...                                                ...
117  40.5                                         Mauritania
118  33.0                                               Mali
119  41.5                                     CÃÂ´te d\Ivoire
120  37.9                                           Cambodia
121  45.5                                        South Sudan
122  42.8                                              Ghana
123  26.4                                            Ukraine
124  44.3                                             Uganda
125  39.8                                       Burkina Faso
126  34.6                                              Niger
127  39.0                                             Malawi
128  39.8                                               Chad
129   NaN                                           Zimbabwe
130  52.5                                            Lesotho
131  58.6                                             Angola
132  27.8                                        Afghanistan
133  61.0                                           Botswana
134  38.6                                              Benin
135  44.1                                         Madagascar
136  59.2                                              Haiti
137  37.7                                              Yemen
138  45.5                                        South Sudan
139  38.2                                            Liberia
140   NaN                                  Equatorial Guinea
141  34.4                                               Togo
142  50.8                                             Rwanda
143  35.8                               Syrian Arab Republic
144  37.6                       Tanzania, United Republic of
145  33.3                                            Burundi
146  56.3                           Central African Republic

[147 rows x 2 columns]