# Get GINI Index from API

In [1]:
import pandas as pd
import numpy as np
import requests

In [17]:
# List of Countries most happiest and least happiest countries [kaggle: World Happiest Report]

list_of_names = ['Norway', 'Denmark', 'Iceland', 'Switzerland', 'Finland', 'Netherlands','Canada', 'New Zealand', 'Sweden', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'United States of America', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United Kingdom', 'Chile', 'United Arab Emirates', 'Brazil', 'Czech Republic', 'Argentina', 'Mexico', 'Singapore', 'Malta', 'Uruguay', 'Guatemala', 'Panama', 'France', 'Thailand', 'Spain', 'Qatar', 'Colombia', 'Saudi Arabia', 'Trinidad and Tobago', 'Kuwait', 'Slovakia', 'Bahrain', 'Malaysia', 'Nicaragua', 'Ecuador', 'El Salvador', 'Poland', 'Uzbekistan', 'Italy', 'Russia', 'Belize', 'Japan', 'Lithuania', 'Algeria', 'Latvia', 'Moldova', 'Romania', 'Bolivia', 'Turkmenistan', 'Kazakhstan', 'Slovenia', 'Peru', 'Mauritius', 'Cyprus', 'Estonia', 'Belarus', 'Libya', 'Turkey', 'Paraguay', 'Philippines', 'Serbia', 'Jordan', 'Hungary', 'Jamaica', 'Croatia', 'Kosovo', 'China', 'Pakistan', 'Indonesia', 'Venezuela', 'Montenegro', 'Morocco', 'Azerbaijan', 'Dominican Republic', 'Greece', 'Lebanon', 'Portugal', 'Bosnia and Herzegovina', 'Honduras', 'Macedonia', 'Somalia', 'Vietnam', 'Nigeria', 'Tajikistan', 'Bhutan', 'Kyrgyzstan', 'Nepal', 'Mongolia', 'South Africa', 'Tunisia', 'Egypt', 'Bulgaria', 'Sierra Leone', 'Cameroon', 'Iran', 'Albania', 'Bangladesh', 'Namibia', 'Kenya', 'Mozambique', 'Myanmar', 'Senegal', 'Zambia', 'Iraq', 'Gabon', 'Ethiopia', 'Sri Lanka', 'Armenia', 'India', 'Mauritania', 'Mali', 'Ivory Coast', 'Cambodia', 'Sudan', 'Ghana', 'Ukraine', 'Uganda', 'Burkina Faso', 'Niger', 'Malawi', 'Chad', 'Zimbabwe', 'Lesotho', 'Angola', 'Afghanistan', 'Botswana', 'Benin', 'Madagascar', 'Haiti', 'Yemen', 'South Sudan', 'Liberia', 'Guinea', 'Togo', 'Rwanda', 'Syria', 'Tanzania', 'Burundi', 'Central African Republic']

fields = "?fields=alpha3Code;name"
url = "https://restcountries.eu/rest/v2/name/"



contents = [requests.get(url + list_of_names[x] + fields).json() for x in range(len(list_of_names))]

print(contents)

[[{'name': 'Norway', 'alpha3Code': 'NOR'}], [{'name': 'Denmark', 'alpha3Code': 'DNK'}], [{'name': 'Iceland', 'alpha3Code': 'ISL'}], [{'name': 'Switzerland', 'alpha3Code': 'CHE'}], [{'name': 'Finland', 'alpha3Code': 'FIN'}], [{'name': 'Netherlands', 'alpha3Code': 'NLD'}], [{'name': 'Canada', 'alpha3Code': 'CAN'}], [{'name': 'New Zealand', 'alpha3Code': 'NZL'}], [{'name': 'Sweden', 'alpha3Code': 'SWE'}], [{'name': 'Australia', 'alpha3Code': 'AUS'}], [{'name': 'Israel', 'alpha3Code': 'ISR'}], [{'name': 'Costa Rica', 'alpha3Code': 'CRI'}], [{'name': 'Austria', 'alpha3Code': 'AUT'}], [{'name': 'United States of America', 'alpha3Code': 'USA'}], [{'name': 'Ireland', 'alpha3Code': 'IRL'}, {'name': 'United Kingdom of Great Britain and Northern Ireland', 'alpha3Code': 'GBR'}], [{'name': 'Germany', 'alpha3Code': 'DEU'}], [{'name': 'Belgium', 'alpha3Code': 'BEL'}], [{'name': 'Luxembourg', 'alpha3Code': 'LUX'}], [{'name': 'United Kingdom of Great Britain and Northern Ireland', 'alpha3Code': 'GBR'}], [{'name': 'Chile', 'alpha3Code': 'CHL'}], [{'name': 'United Arab Emirates', 'alpha3Code': 'ARE'}], [{'name': 'Brazil', 'alpha3Code': 'BRA'}], [{'name': 'Czech Republic', 'alpha3Code': 'CZE'}], [{'name': 'Argentina', 'alpha3Code': 'ARG'}], [{'name': 'Mexico', 'alpha3Code': 'MEX'}], [{'name': 'Singapore', 'alpha3Code': 'SGP'}], [{'name': 'Malta', 'alpha3Code': 'MLT'}], [{'name': 'Uruguay', 'alpha3Code': 'URY'}], [{'name': 'Guatemala', 'alpha3Code': 'GTM'}], [{'name': 'Panama', 'alpha3Code': 'PAN'}], [{'name': 'France', 'alpha3Code': 'FRA'}], [{'name': 'Thailand', 'alpha3Code': 'THA'}], [{'name': 'Spain', 'alpha3Code': 'ESP'}], [{'name': 'Qatar', 'alpha3Code': 'QAT'}], [{'name': 'Colombia', 'alpha3Code': 'COL'}], [{'name': 'Saudi Arabia', 'alpha3Code': 'SAU'}], [{'name': 'Trinidad and Tobago', 'alpha3Code': 'TTO'}], [{'name': 'Kuwait', 'alpha3Code': 'KWT'}], [{'name': 'Slovakia', 'alpha3Code': 'SVK'}], [{'name': 'Bahrain', 'alpha3Code': 'BHR'}], [{'name': 'Malaysia', 'alpha3Code': 'MYS'}], [{'name': 'Nicaragua', 'alpha3Code': 'NIC'}], [{'name': 'Ecuador', 'alpha3Code': 'ECU'}], [{'name': 'El Salvador', 'alpha3Code': 'SLV'}], [{'name': 'Poland', 'alpha3Code': 'POL'}], [{'name': 'Uzbekistan', 'alpha3Code': 'UZB'}], [{'name': 'Italy', 'alpha3Code': 'ITA'}], [{'name': 'Russian Federation', 'alpha3Code': 'RUS'}], [{'name': 'Belize', 'alpha3Code': 'BLZ'}], [{'name': 'Japan', 'alpha3Code': 'JPN'}], [{'name': 'Lithuania', 'alpha3Code': 'LTU'}], [{'name': 'Algeria', 'alpha3Code': 'DZA'}], [{'name': 'Latvia', 'alpha3Code': 'LVA'}], [{'name': 'Moldova (Republic of)', 'alpha3Code': 'MDA'}], [{'name': 'Romania', 'alpha3Code': 'ROU'}], [{'name': 'Bolivia (Plurinational State of)', 'alpha3Code': 'BOL'}], [{'name': 'Turkmenistan', 'alpha3Code': 'TKM'}], [{'name': 'Kazakhstan', 'alpha3Code': 'KAZ'}], [{'name': 'Slovenia', 'alpha3Code': 'SVN'}], [{'name': 'Peru', 'alpha3Code': 'PER'}], [{'name': 'Mauritius', 'alpha3Code': 'MUS'}], [{'name': 'Cyprus', 'alpha3Code': 'CYP'}], [{'name': 'Estonia', 'alpha3Code': 'EST'}], [{'name': 'Belarus', 'alpha3Code': 'BLR'}], [{'name': 'Libya', 'alpha3Code': 'LBY'}], [{'name': 'Turkey', 'alpha3Code': 'TUR'}], [{'name': 'Paraguay', 'alpha3Code': 'PRY'}], [{'name': 'Philippines', 'alpha3Code': 'PHL'}], [{'name': 'Serbia', 'alpha3Code': 'SRB'}], [{'name': 'Jordan', 'alpha3Code': 'JOR'}], [{'name': 'Hungary', 'alpha3Code': 'HUN'}], [{'name': 'Jamaica', 'alpha3Code': 'JAM'}], [{'name': 'Croatia', 'alpha3Code': 'HRV'}], [{'name': 'Republic of Kosovo', 'alpha3Code': 'KOS'}], [{'name': 'China', 'alpha3Code': 'CHN'}, {'name': 'Macao', 'alpha3Code': 'MAC'}, {'name': 'Taiwan', 'alpha3Code': 'TWN'}], [{'name': 'Pakistan', 'alpha3Code': 'PAK'}], [{'name': 'Indonesia', 'alpha3Code': 'IDN'}], [{'name': 'Venezuela (Bolivarian Republic of)', 'alpha3Code': 'VEN'}], [{'name': 'Montenegro', 'alpha3Code': 'MNE'}], [{'name': 'Morocco', 'alpha3Code': 'MAR'}], [{'name': 'Azerbaijan', 'alpha3Code': 'AZE'}], [{'name': 'Dominican Republic', 'alpha3Code': 'DOM'}], [{'name': 'Greece', 'alpha3Code': 'GRC'}], [{'name': 'Lebanon', 'alpha3Code': 'LBN'}], [{'name': 'Portugal', 'alpha3Code': 'PRT'}], [{'name': 'Bosnia and Herzegovina', 'alpha3Code': 'BIH'}], [{'name': 'Honduras', 'alpha3Code': 'HND'}], [{'name': 'Macedonia (the former Yugoslav Republic of)', 'alpha3Code': 'MKD'}], [{'name': 'Somalia', 'alpha3Code': 'SOM'}], [{'name': 'Viet Nam', 'alpha3Code': 'VNM'}], [{'name': 'Nigeria', 'alpha3Code': 'NGA'}], [{'name': 'Tajikistan', 'alpha3Code': 'TJK'}], [{'name': 'Bhutan', 'alpha3Code': 'BTN'}], [{'name': 'Kyrgyzstan', 'alpha3Code': 'KGZ'}], [{'name': 'Nepal', 'alpha3Code': 'NPL'}], [{'name': 'Mongolia', 'alpha3Code': 'MNG'}], [{'name': 'South Africa', 'alpha3Code': 'ZAF'}], [{'name': 'Tunisia', 'alpha3Code': 'TUN'}], [{'name': 'Egypt', 'alpha3Code': 'EGY'}], [{'name': 'Bulgaria', 'alpha3Code': 'BGR'}], [{'name': 'Sierra Leone', 'alpha3Code': 'SLE'}], [{'name': 'Cameroon', 'alpha3Code': 'CMR'}], [{'name': 'Iran (Islamic Republic of)', 'alpha3Code': 'IRN'}, {'name': 'Cook Islands', 'alpha3Code': 'COK'}], [{'name': 'Albania', 'alpha3Code': 'ALB'}], [{'name': 'Bangladesh', 'alpha3Code': 'BGD'}], [{'name': 'Namibia', 'alpha3Code': 'NAM'}], [{'name': 'Kenya', 'alpha3Code': 'KEN'}], [{'name': 'Mozambique', 'alpha3Code': 'MOZ'}], [{'name': 'Myanmar', 'alpha3Code': 'MMR'}], [{'name': 'Senegal', 'alpha3Code': 'SEN'}], [{'name': 'Zambia', 'alpha3Code': 'ZMB'}], [{'name': 'Iraq', 'alpha3Code': 'IRQ'}], [{'name': 'Gabon', 'alpha3Code': 'GAB'}], [{'name': 'Ethiopia', 'alpha3Code': 'ETH'}], [{'name': 'Sri Lanka', 'alpha3Code': 'LKA'}], [{'name': 'Armenia', 'alpha3Code': 'ARM'}], [{'name': 'British Indian Ocean Territory', 'alpha3Code': 'IOT'}, {'name': 'India', 'alpha3Code': 'IND'}], [{'name': 'Mauritania', 'alpha3Code': 'MRT'}], [{'name': 'Mali', 'alpha3Code': 'MLI'}, {'name': 'Somalia', 'alpha3Code': 'SOM'}], [{'name': "CÃ´te d'Ivoire", 'alpha3Code': 'CIV'}], [{'name': 'Cambodia', 'alpha3Code': 'KHM'}], [{'name': 'South Sudan', 'alpha3Code': 'SSD'}, {'name': 'Sudan', 'alpha3Code': 'SDN'}], [{'name': 'Ghana', 'alpha3Code': 'GHA'}], [{'name': 'Ukraine', 'alpha3Code': 'UKR'}], [{'name': 'Uganda', 'alpha3Code': 'UGA'}], [{'name': 'Burkina Faso', 'alpha3Code': 'BFA'}], [{'name': 'Niger', 'alpha3Code': 'NER'}, {'name': 'Nigeria', 'alpha3Code': 'NGA'}], [{'name': 'Malawi', 'alpha3Code': 'MWI'}], [{'name': 'Chad', 'alpha3Code': 'TCD'}], [{'name': 'Zimbabwe', 'alpha3Code': 'ZWE'}], [{'name': 'Lesotho', 'alpha3Code': 'LSO'}], [{'name': 'Angola', 'alpha3Code': 'AGO'}], [{'name': 'Afghanistan', 'alpha3Code': 'AFG'}], [{'name': 'Botswana', 'alpha3Code': 'BWA'}], [{'name': 'Benin', 'alpha3Code': 'BEN'}], [{'name': 'Madagascar', 'alpha3Code': 'MDG'}], [{'name': 'Haiti', 'alpha3Code': 'HTI'}], [{'name': 'Yemen', 'alpha3Code': 'YEM'}], [{'name': 'South Sudan', 'alpha3Code': 'SSD'}], [{'name': 'Liberia', 'alpha3Code': 'LBR'}], [{'name': 'Equatorial Guinea', 'alpha3Code': 'GNQ'}, {'name': 'Guinea', 'alpha3Code': 'GIN'}, {'name': 'Guinea-Bissau', 'alpha3Code': 'GNB'}, {'name': 'Papua New Guinea', 'alpha3Code': 'PNG'}], [{'name': 'Togo', 'alpha3Code': 'TGO'}], [{'name': 'Rwanda', 'alpha3Code': 'RWA'}], [{'name': 'Syrian Arab Republic', 'alpha3Code': 'SYR'}], [{'name': 'Tanzania, United Republic of', 'alpha3Code': 'TZA'}], [{'name': 'Burundi', 'alpha3Code': 'BDI'}], [{'name': 'Central African Republic', 'alpha3Code': 'CAF'}]]

In [18]:
d_contents = pd.DataFrame(contents)
d_contents
#[ d_contents[i]  for i in range(len(d_contents))if d_contents[i]=="status"]

                                                     0     1     2     3
0              {'name': 'Norway', 'alpha3Code': 'NOR'}  None  None  None
1             {'name': 'Denmark', 'alpha3Code': 'DNK'}  None  None  None
2             {'name': 'Iceland', 'alpha3Code': 'ISL'}  None  None  None
3         {'name': 'Switzerland', 'alpha3Code': 'CHE'}  None  None  None
4             {'name': 'Finland', 'alpha3Code': 'FIN'}  None  None  None
..                                                 ...   ...   ...   ...
142            {'name': 'Rwanda', 'alpha3Code': 'RWA'}  None  None  None
143  {'name': 'Syrian Arab Republic', 'alpha3Code':...  None  None  None
144  {'name': 'Tanzania, United Republic of', 'alph...  None  None  None
145           {'name': 'Burundi', 'alpha3Code': 'BDI'}  None  None  None
146  {'name': 'Central African Republic', 'alpha3Co...  None  None  None

[147 rows x 4 columns]

In [19]:
# Extend Country name with Code (alpha3Code) [Source: API]

country_code =[d_contents[0][i] for i in range(len(d_contents))]
ds = pd.DataFrame.from_dict([country_code[i] for i in range(len(d_contents))])
ds

                             name alpha3Code
0                          Norway        NOR
1                         Denmark        DNK
2                         Iceland        ISL
3                     Switzerland        CHE
4                         Finland        FIN
..                            ...        ...
142                        Rwanda        RWA
143          Syrian Arab Republic        SYR
144  Tanzania, United Republic of        TZA
145                       Burundi        BDI
146      Central African Republic        CAF

[147 rows x 2 columns]

In [20]:
# Merge Data of API (Gini-Index) with Country Name (WH-Report)

codes = list(ds["alpha3Code"])
codes

fields2 = "?fields=gini;name"
url2 = "https://restcountries.eu/rest/v2/alpha/"

ginis = [requests.get(url2 + codes[x] + fields2).content for x in range(len(codes))]

print(ginis)

[b'{"name":"Norway","gini":25.8}', b'{"name":"Denmark","gini":24.0}', b'{"name":"Iceland"}', b'{"name":"Switzerland","gini":33.7}', b'{"name":"Finland","gini":26.9}', b'{"name":"Netherlands","gini":30.9}', b'{"name":"Canada","gini":32.6}', b'{"name":"New Zealand","gini":36.2}', b'{"name":"Sweden","gini":25.0}', b'{"name":"Australia","gini":30.5}', b'{"name":"Israel","gini":39.2}', b'{"name":"Costa Rica","gini":50.7}', b'{"name":"Austria","gini":26.0}', b'{"name":"United States of America","gini":48.0}', b'{"name":"Ireland","gini":34.3}', b'{"name":"Germany","gini":28.3}', b'{"name":"Belgium","gini":33.0}', b'{"name":"Luxembourg","gini":30.8}', b'{"name":"United Kingdom of Great Britain and Northern Ireland","gini":34.0}', b'{"name":"Chile","gini":52.1}', b'{"name":"United Arab Emirates"}', b'{"name":"Brazil","gini":54.7}', b'{"name":"Czech Republic","gini":26.0}', b'{"name":"Argentina","gini":44.5}', b'{"name":"Mexico","gini":47.0}', b'{"name":"Singapore","gini":48.1}', b'{"name":"Malta"}', b'{"name":"Uruguay","gini":39.7}', b'{"name":"Guatemala","gini":55.9}', b'{"name":"Panama","gini":51.9}', b'{"name":"France","gini":32.7}', b'{"name":"Thailand","gini":40.0}', b'{"name":"Spain","gini":34.7}', b'{"name":"Qatar","gini":41.1}', b'{"name":"Colombia","gini":55.9}', b'{"name":"Saudi Arabia"}', b'{"name":"Trinidad and Tobago","gini":40.3}', b'{"name":"Kuwait"}', b'{"name":"Slovakia","gini":26.0}', b'{"name":"Bahrain"}', b'{"name":"Malaysia","gini":46.2}', b'{"name":"Nicaragua","gini":40.5}', b'{"name":"Ecuador","gini":49.3}', b'{"name":"El Salvador","gini":48.3}', b'{"name":"Poland","gini":34.1}', b'{"name":"Uzbekistan","gini":36.7}', b'{"name":"Italy","gini":36.0}', b'{"name":"Russian Federation","gini":40.1}', b'{"name":"Belize","gini":53.1}', b'{"name":"Japan","gini":38.1}', b'{"name":"Lithuania","gini":37.6}', b'{"name":"Algeria","gini":35.3}', b'{"name":"Latvia","gini":36.6}', b'{"name":"Moldova (Republic of)","gini":33.0}', b'{"name":"Romania","gini":30.0}', b'{"name":"Bolivia (Plurinational State of)","gini":56.3}', b'{"name":"Turkmenistan","gini":40.8}', b'{"name":"Kazakhstan","gini":29.0}', b'{"name":"Slovenia","gini":31.2}', b'{"name":"Peru","gini":48.1}', b'{"name":"Mauritius"}', b'{"name":"Cyprus"}', b'{"name":"Estonia","gini":36.0}', b'{"name":"Belarus","gini":26.5}', b'{"name":"Libya"}', b'{"name":"Turkey","gini":39.0}', b'{"name":"Paraguay","gini":52.4}', b'{"name":"Philippines","gini":43.0}', b'{"name":"Serbia","gini":27.8}', b'{"name":"Jordan","gini":35.4}', b'{"name":"Hungary","gini":31.2}', b'{"name":"Jamaica","gini":45.5}', b'{"name":"Croatia","gini":33.7}', b'{"name":"Republic of Kosovo"}', b'{"name":"China","gini":47.0}', b'{"name":"Pakistan","gini":30.0}', b'{"name":"Indonesia","gini":34.0}', b'{"name":"Venezuela (Bolivarian Republic of)","gini":44.8}', b'{"name":"Montenegro","gini":30.0}', b'{"name":"Morocco","gini":40.9}', b'{"name":"Azerbaijan","gini":33.7}', b'{"name":"Dominican Republic","gini":47.2}', b'{"name":"Greece","gini":34.3}', b'{"name":"Lebanon"}', b'{"name":"Portugal","gini":38.5}', b'{"name":"Bosnia and Herzegovina","gini":36.2}', b'{"name":"Honduras","gini":57.0}', b'{"name":"Macedonia (the former Yugoslav Republic of)","gini":43.2}', b'{"name":"Somalia"}', b'{"name":"Viet Nam","gini":35.6}', b'{"name":"Nigeria","gini":48.8}', b'{"name":"Tajikistan","gini":30.8}', b'{"name":"Bhutan","gini":38.1}', b'{"name":"Kyrgyzstan","gini":36.2}', b'{"name":"Nepal","gini":32.8}', b'{"name":"Mongolia","gini":36.5}', b'{"name":"South Africa","gini":63.1}', b'{"name":"Tunisia","gini":41.4}', b'{"name":"Egypt","gini":30.8}', b'{"name":"Bulgaria","gini":28.2}', b'{"name":"Sierra Leone","gini":42.5}', b'{"name":"Cameroon","gini":38.9}', b'{"name":"Iran (Islamic Republic of)","gini":38.3}', b'{"name":"Albania","gini":34.5}', b'{"name":"Bangladesh","gini":32.1}', b'{"name":"Namibia","gini":63.9}', b'{"name":"Kenya","gini":47.7}', b'{"name":"Mozambique","gini":45.7}', b'{"name":"Myanmar"}', b'{"name":"Senegal","gini":39.2}', b'{"name":"Zambia","gini":54.6}', b'{"name":"Iraq","gini":30.9}', b'{"name":"Gabon","gini":41.5}', b'{"name":"Ethiopia","gini":29.8}', b'{"name":"Sri Lanka","gini":40.3}', b'{"name":"Armenia","gini":30.9}', b'{"name":"British Indian Ocean Territory"}', b'{"name":"Mauritania","gini":40.5}', b'{"name":"Mali","gini":33.0}', b'{"name":"C\xc3\xb4te d\'Ivoire","gini":41.5}', b'{"name":"Cambodia","gini":37.9}', b'{"name":"South Sudan","gini":45.5}', b'{"name":"Ghana","gini":42.8}', b'{"name":"Ukraine","gini":26.4}', b'{"name":"Uganda","gini":44.3}', b'{"name":"Burkina Faso","gini":39.8}', b'{"name":"Niger","gini":34.6}', b'{"name":"Malawi","gini":39.0}', b'{"name":"Chad","gini":39.8}', b'{"name":"Zimbabwe"}', b'{"name":"Lesotho","gini":52.5}', b'{"name":"Angola","gini":58.6}', b'{"name":"Afghanistan","gini":27.8}', b'{"name":"Botswana","gini":61.0}', b'{"name":"Benin","gini":38.6}', b'{"name":"Madagascar","gini":44.1}', b'{"name":"Haiti","gini":59.2}', b'{"name":"Yemen","gini":37.7}', b'{"name":"South Sudan","gini":45.5}', b'{"name":"Liberia","gini":38.2}', b'{"name":"Equatorial Guinea"}', b'{"name":"Togo","gini":34.4}', b'{"name":"Rwanda","gini":50.8}', b'{"name":"Syrian Arab Republic","gini":35.8}', b'{"name":"Tanzania, United Republic of","gini":37.6}', b'{"name":"Burundi","gini":33.3}', b'{"name":"Central African Republic","gini":56.3}']

In [22]:
# Transformation

new =[ginis[i] for i in range(len(d_contents))]
new[0]
new1 = [str(new[i]).replace("b'","").replace("'", "") for i in range(len(new))]
print(new1)
new1[0]

import ast

dict_gini = [ast.literal_eval(new1[i]) for i in range(len(new1))]

['{"name":"Norway","gini":25.8}', '{"name":"Denmark","gini":24.0}', '{"name":"Iceland"}', '{"name":"Switzerland","gini":33.7}', '{"name":"Finland","gini":26.9}', '{"name":"Netherlands","gini":30.9}', '{"name":"Canada","gini":32.6}', '{"name":"New Zealand","gini":36.2}', '{"name":"Sweden","gini":25.0}', '{"name":"Australia","gini":30.5}', '{"name":"Israel","gini":39.2}', '{"name":"Costa Rica","gini":50.7}', '{"name":"Austria","gini":26.0}', '{"name":"United States of America","gini":48.0}', '{"name":"Ireland","gini":34.3}', '{"name":"Germany","gini":28.3}', '{"name":"Belgium","gini":33.0}', '{"name":"Luxembourg","gini":30.8}', '{"name":"United Kingdom of Great Britain and Northern Ireland","gini":34.0}', '{"name":"Chile","gini":52.1}', '{"name":"United Arab Emirates"}', '{"name":"Brazil","gini":54.7}', '{"name":"Czech Republic","gini":26.0}', '{"name":"Argentina","gini":44.5}', '{"name":"Mexico","gini":47.0}', '{"name":"Singapore","gini":48.1}', '{"name":"Malta"}', '{"name":"Uruguay","gini":39.7}', '{"name":"Guatemala","gini":55.9}', '{"name":"Panama","gini":51.9}', '{"name":"France","gini":32.7}', '{"name":"Thailand","gini":40.0}', '{"name":"Spain","gini":34.7}', '{"name":"Qatar","gini":41.1}', '{"name":"Colombia","gini":55.9}', '{"name":"Saudi Arabia"}', '{"name":"Trinidad and Tobago","gini":40.3}', '{"name":"Kuwait"}', '{"name":"Slovakia","gini":26.0}', '{"name":"Bahrain"}', '{"name":"Malaysia","gini":46.2}', '{"name":"Nicaragua","gini":40.5}', '{"name":"Ecuador","gini":49.3}', '{"name":"El Salvador","gini":48.3}', '{"name":"Poland","gini":34.1}', '{"name":"Uzbekistan","gini":36.7}', '{"name":"Italy","gini":36.0}', '{"name":"Russian Federation","gini":40.1}', '{"name":"Belize","gini":53.1}', '{"name":"Japan","gini":38.1}', '{"name":"Lithuania","gini":37.6}', '{"name":"Algeria","gini":35.3}', '{"name":"Latvia","gini":36.6}', '{"name":"Moldova (Republic of)","gini":33.0}', '{"name":"Romania","gini":30.0}', '{"name":"Bolivia (Plurinational State of)","gini":56.3}', '{"name":"Turkmenistan","gini":40.8}', '{"name":"Kazakhstan","gini":29.0}', '{"name":"Slovenia","gini":31.2}', '{"name":"Peru","gini":48.1}', '{"name":"Mauritius"}', '{"name":"Cyprus"}', '{"name":"Estonia","gini":36.0}', '{"name":"Belarus","gini":26.5}', '{"name":"Libya"}', '{"name":"Turkey","gini":39.0}', '{"name":"Paraguay","gini":52.4}', '{"name":"Philippines","gini":43.0}', '{"name":"Serbia","gini":27.8}', '{"name":"Jordan","gini":35.4}', '{"name":"Hungary","gini":31.2}', '{"name":"Jamaica","gini":45.5}', '{"name":"Croatia","gini":33.7}', '{"name":"Republic of Kosovo"}', '{"name":"China","gini":47.0}', '{"name":"Pakistan","gini":30.0}', '{"name":"Indonesia","gini":34.0}', '{"name":"Venezuela (Bolivarian Republic of)","gini":44.8}', '{"name":"Montenegro","gini":30.0}', '{"name":"Morocco","gini":40.9}', '{"name":"Azerbaijan","gini":33.7}', '{"name":"Dominican Republic","gini":47.2}', '{"name":"Greece","gini":34.3}', '{"name":"Lebanon"}', '{"name":"Portugal","gini":38.5}', '{"name":"Bosnia and Herzegovina","gini":36.2}', '{"name":"Honduras","gini":57.0}', '{"name":"Macedonia (the former Yugoslav Republic of)","gini":43.2}', '{"name":"Somalia"}', '{"name":"Viet Nam","gini":35.6}', '{"name":"Nigeria","gini":48.8}', '{"name":"Tajikistan","gini":30.8}', '{"name":"Bhutan","gini":38.1}', '{"name":"Kyrgyzstan","gini":36.2}', '{"name":"Nepal","gini":32.8}', '{"name":"Mongolia","gini":36.5}', '{"name":"South Africa","gini":63.1}', '{"name":"Tunisia","gini":41.4}', '{"name":"Egypt","gini":30.8}', '{"name":"Bulgaria","gini":28.2}', '{"name":"Sierra Leone","gini":42.5}', '{"name":"Cameroon","gini":38.9}', '{"name":"Iran (Islamic Republic of)","gini":38.3}', '{"name":"Albania","gini":34.5}', '{"name":"Bangladesh","gini":32.1}', '{"name":"Namibia","gini":63.9}', '{"name":"Kenya","gini":47.7}', '{"name":"Mozambique","gini":45.7}', '{"name":"Myanmar"}', '{"name":"Senegal","gini":39.2}', '{"name":"Zambia","gini":54.6}', '{"name":"Iraq","gini":30.9}', '{"name":"Gabon","gini":41.5}', '{"name":"Ethiopia","gini":29.8}', '{"name":"Sri Lanka","gini":40.3}', '{"name":"Armenia","gini":30.9}', '{"name":"British Indian Ocean Territory"}', '{"name":"Mauritania","gini":40.5}', '{"name":"Mali","gini":33.0}', '{"name":"C\\xc3\\xb4te d\\Ivoire","gini":41.5}', '{"name":"Cambodia","gini":37.9}', '{"name":"South Sudan","gini":45.5}', '{"name":"Ghana","gini":42.8}', '{"name":"Ukraine","gini":26.4}', '{"name":"Uganda","gini":44.3}', '{"name":"Burkina Faso","gini":39.8}', '{"name":"Niger","gini":34.6}', '{"name":"Malawi","gini":39.0}', '{"name":"Chad","gini":39.8}', '{"name":"Zimbabwe"}', '{"name":"Lesotho","gini":52.5}', '{"name":"Angola","gini":58.6}', '{"name":"Afghanistan","gini":27.8}', '{"name":"Botswana","gini":61.0}', '{"name":"Benin","gini":38.6}', '{"name":"Madagascar","gini":44.1}', '{"name":"Haiti","gini":59.2}', '{"name":"Yemen","gini":37.7}', '{"name":"South Sudan","gini":45.5}', '{"name":"Liberia","gini":38.2}', '{"name":"Equatorial Guinea"}', '{"name":"Togo","gini":34.4}', '{"name":"Rwanda","gini":50.8}', '{"name":"Syrian Arab Republic","gini":35.8}', '{"name":"Tanzania, United Republic of","gini":37.6}', '{"name":"Burundi","gini":33.3}', '{"name":"Central African Republic","gini":56.3}']

In [30]:
# Connect Gini-Index with Country Name

ds_gini = pd.DataFrame.from_dict([dict_gini[i] for i in range(len(new1))])
ds_gini

                             name  gini
0                          Norway  25.8
1                         Denmark  24.0
2                         Iceland   NaN
3                     Switzerland  33.7
4                         Finland  26.9
..                            ...   ...
142                        Rwanda  50.8
143          Syrian Arab Republic  35.8
144  Tanzania, United Republic of  37.6
145                       Burundi  33.3
146      Central African Republic  56.3

[147 rows x 2 columns]

In [32]:
ds_gini.to_csv(r"C:\Users\linda\Ironhack\Projects\Project_3\gini_per_country_1.csv")